'use strict';
/* ================= professional documents (quotation / invoice) =================
   Renders an A4-style document on screen and prints it via the browser dialog
   (choose "Save as PDF"). Fully offline — no external PDF library. */

function docBusinessBlock(){
  const b = db.business;
  const logo = b.logo ? `<img class="doc-logo" src="${b.logo}" alt="logo">` : '';
  return `<div class="doc-biz">
    ${logo}
    <div>
      <div class="doc-biz-name">${esc(b.name)}</div>
      <div class="doc-biz-meta">
        ${b.address ? esc(b.address) + '<br>' : ''}
        ${b.phone ? esc(b.phone) : ''}${b.email ? ' · ' + esc(b.email) : ''}
      </div>
    </div>
  </div>`;
}

function docHeader(kind, ref, dateLines){
  return `<div class="doc-top">
    ${docBusinessBlock()}
    <div class="doc-doctype">
      <div class="doc-doctype-title">${kind}</div>
      <div class="doc-ref">${esc(ref)}</div>
      ${dateLines}
    </div>
  </div>`;
}

function docItemsTable(items, {showUnit=true} = {}){
  return `<table class="doc-table">
    <thead><tr><th>Description</th><th class="num">Qty</th>${showUnit?'<th class="num">Unit</th>':''}<th class="num">Rate</th><th class="num">Amount</th></tr></thead>
    <tbody>
      ${items.map(i => `<tr>
        <td>${esc(i.desc)}</td>
        <td class="num">${i.qty}</td>
        ${showUnit?`<td class="num">${esc(i.unit||'')}</td>`:''}
        <td class="num">${money(i.price)}</td>
        <td class="num">${money((i.qty||0)*(i.price||0))}</td>
      </tr>`).join('')}
    </tbody>
  </table>`;
}

function docTotals(sub, disc, vat, total){
  const vatAmt = total - Math.round((sub - disc) * (1 + vat/100));
  return `<div class="doc-totals">
    <div class="r"><span>Subtotal</span><span>${money(sub)}</span></div>
    ${disc ? `<div class="r"><span>Discount</span><span>− ${money(disc)}</span></div>` : ''}
    <div class="r"><span>VAT (${vat}%)</span><span>${money(vatAmt)}</span></div>
    <div class="r tot"><span>TOTAL (${esc(db.business.currency||'KES')})</span><span>${money(total)}</span></div>
  </div>`;
}

function docSignatures(left, right){
  return `<div class="doc-sig">
    <div><div class="sig-line"></div><div class="muted small">${esc(left||'Prepared by')}</div></div>
    <div><div class="sig-line"></div><div class="muted small">${esc(right||'Authorised signature / stamp')}</div></div>
  </div>`;
}

function docFooter(){
  const b = db.business;
  return `<div class="doc-foot">
    ${esc(b.name)}${b.phone ? ' · ' + esc(b.phone) : ''}${b.email ? ' · ' + esc(b.email) : ''}<br>
    Generated by AquaFlow PMS on ${fmtDateFull(isoDate(today()))} · Thank you for your business.
  </div>`;
}

function quoteDocHTML(q){
  const c = customerById(q.customerId);
  const sub = quoteSubtotal(q);
  const total = quoteTotal(q);
  return `<div class="doc-sheet" id="doc-sheet">
    ${docHeader('QUOTATION', q.ref, `
      <div class="doc-lines">
        <div>Quoted on: <b>${fmtDate(q.createdAt)}</b></div>
        <div>Valid until: <b>${fmtDate(q.validUntil)}</b></div>
        <div>Payment terms: <b>${db.business.dueDays||14} days</b></div>
      </div>`)}
    <div class="doc-cust">
      <div><span class="muted small">Prepared for</span><b>${esc(c?c.name:'—')}</b>
        <div class="muted small">${esc(c?(c.area||''):'')}${c&&c.phone?' · '+esc(c.phone):''}${c&&c.email?' · '+esc(c.email):''}</div>
      </div>
      ${q.jobId ? `<div class="muted small">Related job: <b>${esc(jobById(q.jobId)?.ref||'')}</b></div>` : ''}
    </div>
    ${q.title ? `<div class="doc-title">Re: ${esc(q.title)}</div>` : ''}
    ${docItemsTable(q.items)}
    ${docTotals(sub, q.discount||0, q.vatRate||0, total)}
    ${q.notes ? `<div class="doc-notes"><b>Notes / terms:</b> ${esc(q.notes)}</div>` : ''}
    ${docSignatures()}
    ${docFooter()}
  </div>`;
}

function invoiceDocHTML(inv){
  const c = customerById(inv.customerId);
  const st = invState(inv);
  const sub = invSubtotal(inv);
  const total = invTotal(inv);
  const job = inv.jobId ? jobById(inv.jobId) : null;
  return `<div class="doc-sheet" id="doc-sheet">
    ${docHeader('INVOICE', inv.ref, `
      <div class="doc-lines">
        <div>Issued: <b>${fmtDate(inv.issued)}</b></div>
        <div>Due: <b>${fmtDate(inv.due)}</b></div>
        <div>Status: <b>${st.label}</b></div>
      </div>`)}
    <div class="doc-cust">
      <div><span class="muted small">Bill to</span><b>${esc(c?c.name:'—')}</b>
        <div class="muted small">${esc(c?(c.area||''):'')}${c&&c.phone?' · '+esc(c.phone):''}${c&&c.email?' · '+esc(c.email):''}</div>
      </div>
      ${job ? `<div class="muted small">For job: <b>${job.ref} — ${esc(job.title)}</b> (${fmtDateShort(job.date)})</div>` : ''}
    </div>
    ${docItemsTable(inv.items)}
    ${docTotals(sub, inv.discount||0, inv.vatRate||0, total)}
    <div class="doc-paidbox">
      <div class="r"><span>Amount paid</span><span>${money(invPaid(inv))}</span></div>
      <div class="r tot"><span>Balance due</span><span>${money(st.balance)}</span></div>
      ${(inv.payments||[]).length ? `<div class="muted small mt8">Payment methods: ${[...new Set((inv.payments||[]).map(p=>p.method))].join(', ')}</div>` : ''}
    </div>
    <div class="doc-notes"><b>Payment:</b> M-Pesa / cash / bank transfer. Quote ref ${esc(inv.quoteRef||'—')} where applicable. Thank you.</div>
    ${docSignatures()}
    ${docFooter()}
  </div>`;
}

function openDoc(kind, id){
  const root = document.getElementById('print-root');
  if(!root) return;
  const q = kind === 'quote' ? quoteById(id) : null;
  const inv = kind === 'invoice' ? invoiceById(id) : null;
  const body = q ? quoteDocHTML(q) : inv ? invoiceDocHTML(inv) : '';
  if(!body) return;
  const label = kind === 'quote' ? 'Quotation' : 'Invoice';
  const ref = q ? q.ref : inv.ref;
  root.innerHTML = `
    <div class="doc-toolbar">
      <b>${label} ${esc(ref)} — preview</b>
      <span class="row">
        <button class="btn ghost sm" id="doc-close">Close</button>
        <button class="btn primary sm" id="doc-print">🖨 Print / Save as PDF</button>
      </span>
    </div>
    ${body}`;
  root.classList.add('open');
  document.body.classList.add('print-doc');
  document.body.classList.add('printing-doc');
  const close = () => closeDoc();
  document.getElementById('doc-close').onclick = close;
  document.getElementById('doc-print').onclick = () => {
    const before = () => {};
    window.addEventListener('afterprint', () => {}, {once:true});
    window.print();
  };
  root.onclick = e => { if(e.target === root) close(); };
}
function closeDoc(){
  const root = document.getElementById('print-root');
  if(root){ root.classList.remove('open'); root.innerHTML = ''; }
  document.body.classList.remove('print-doc');
  document.body.classList.remove('printing-doc');
}
window.__docs = {quote: quoteDocHTML, invoice: invoiceDocHTML};
